#!/usr/bin/env bash
# Investigation A — codebase coupling audit.
#
# Produces a deterministic report of where agent-SDK types and APIs
# leak into piebox's surfaces. Re-run after any refactor to compare
# deltas. Emits markdown on stdout.
#
# Usage:
#   bash scripts/investigations/audit-coupling.sh > docs/investigations/A-codebase-audit.md
#
# Reads:
#   src/                      — piebox core
#   examples/browser/src/     — the in-browser playground
#
# Tracked SDKs (the two agent surfaces leaking today):
#   @earendil-works/pi-coding-agent   — server-side path
#   @earendil-works/pi-agent-core
#   @earendil-works/pi-ai
#   @inbrowser/agent                   — browser-side path (the example)
#   @inbrowser/relay
set -uo pipefail
# `set -e` removed intentionally: many `grep | wc` pipelines below need
# to survive a no-match (grep exit 1) and still count zero.

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

count_imports() {
  local pkg="$1" surface="$2"
  grep -rE "from ['\"]${pkg}" "${surface}" 2>/dev/null | wc -l | tr -d ' '
}

list_files_touching() {
  local pkg="$1" surface="$2"
  grep -rlE "${pkg}" "${surface}" 2>/dev/null | sed "s|^${ROOT}/||" | sort -u
}

list_type_imports() {
  local pkg="$1" surface="$2"
  # Heuristic: between `import {` and `} from "${pkg}"` capture the
  # comma-separated identifier list. Works for both ESM forms.
  grep -B 30 -E "from ['\"]${pkg}" "${surface}"/**/*.ts "${surface}"/**/*.tsx 2>/dev/null \
    | grep -E "^[^/]*[a-zA-Z]" \
    | grep -vE "^--$|^import|^//" \
    | sed -E 's/^.*://; s/,$//; s/^ +//; s/ +$//' \
    | grep -E "^(type )?[A-Z_][a-zA-Z_0-9]*$" \
    | sort -u
}

emit_header() {
  cat <<EOF
# Investigation A — Codebase Coupling Audit

> Generated by \`scripts/investigations/audit-coupling.sh\`.
> Re-run after any refactor to surface deltas.

This audit answers: **where do agent-SDK types and APIs leak into
piebox's surfaces, and how load-bearing are those leaks?** The data
below grounds the architectural decisions D1–D3 in the parent plan.

EOF
}

emit_finding_two_sdks() {
  cat <<EOF
## Finding: piebox today depends on *two* independent agent SDKs

The server-side path (\`src/\`) and the browser playground
(\`examples/browser/src/\`) consume **different agent SDKs**:

| Surface                   | Agent SDK consumed                  |
| ------------------------- | ----------------------------------- |
| \`src/\` (piebox core)    | \`@earendil-works/pi-coding-agent\` |
| \`examples/browser/src/\` | \`@inbrowser/agent\`                |

Neither shares types with the other. The portability and decoupling
work has to deal with both surfaces, not just one. Replacing one SDK
with the other would not improve the architecture; the right move is
a piebox-native Layer 2 that both SDKs can adapt to.

EOF
}

emit_sdk_inventory() {
  local pkg="$1" pretty="$2"
  cat <<EOF
### ${pretty}

EOF
  local src_count examples_count
  src_count=$(count_imports "$pkg" "src")
  examples_count=$(count_imports "$pkg" "examples/browser/src")
  echo "**Import count:** \`src/\` = ${src_count}, \`examples/browser/src/\` = ${examples_count}"
  echo

  local src_files examples_files
  src_files=$(list_files_touching "$pkg" "src")
  examples_files=$(list_files_touching "$pkg" "examples/browser/src")

  if [[ -n "$src_files" ]]; then
    echo "**Files in \`src/\` that import \`${pkg}\`:**"
    echo
    while read -r f; do
      [[ -z "$f" ]] && continue
      echo "- \`${f}\`"
    done <<< "$src_files"
    echo
  fi
  if [[ -n "$examples_files" ]]; then
    echo "**Files in \`examples/browser/src/\` that import \`${pkg}\`:**"
    echo
    while read -r f; do
      [[ -z "$f" ]] && continue
      echo "- \`${f}\`"
    done <<< "$examples_files"
    echo
  fi
}

emit_type_leaks_pi_coding_agent() {
  cat <<EOF
## Detailed leak: \`@earendil-works/pi-coding-agent\` into \`src/operations/\`

Even the layer that *should* be the most protocol-neutral — pure
filesystem operations — pulls its types from an external agent SDK:

\`\`\`
$(grep -h "@earendil-works/pi-coding-agent" src/operations/*.ts | sort -u)
\`\`\`

Each of these operation type aliases (\`ReadOperations\`,
\`WriteOperations\`, etc.) defines the operation's signature inside
\`@earendil-works/pi-coding-agent\`. piebox's \`src/operations/*\`
implements them but doesn't own them.

**Implication for the refactor:** Layer 2 cannot simply re-export
these types — it has to define them piebox-native and have the
existing operations satisfy *those* signatures structurally. Then
the agent SDK can adapt in the driver layer.

EOF
}

emit_browser_surface() {
  cat <<EOF
## Detailed leak: \`@inbrowser/agent\` into \`examples/browser/src/agent.ts\`

Imported identifiers (extracted from each file's import block):

\`\`\`
$(python3 - <<'PY'
import re, pathlib
files = ["examples/browser/src/agent.ts", "examples/browser/src/agent/useAgentLoop.ts"]
for f in files:
    text = pathlib.Path(f).read_text()
    for m in re.finditer(r"import\s*(?:type\s*)?\{([^}]*)\}\s*from\s*['\"]@inbrowser/agent['\"]", text):
        body = m.group(1)
        items = [s.strip().lstrip("type ").strip() for s in body.split(",") if s.strip()]
        print(f"# {f}")
        for it in items:
            print(f"  {it}")
PY
)
\`\`\`

Of these, the **load-bearing types** for the agent driver (would have
to be re-shaped or adapted in a refactor):

- \`ToolHandler\` — the per-tool interface every \`buildTools\` entry implements
- \`ToolContext\` — the runtime arg passed to \`execute()\` (carries \`workspace\`, \`runtime\`, \`signal\`)
- \`ToolResult\` — the return shape (\`ok\`, \`summary\`, \`data\`)
- \`SessionEvent\` — the union the UI \`switch\`es over
- \`ChatMessage\` — used both for store data AND for SDK history round-trip
- \`LlmClient\` / \`LlmConfig\` — the model provider seam
- \`Tracer\` — optional, but agent-SDK-shaped

The **structural types** (\`JsonSchema\`, \`ChatEvent\`) are commodity
shapes that piebox-native equivalents could subsume.

EOF
}

emit_tool_inventory() {
  cat <<EOF
## ToolHandler inventory (\`examples/browser/src/agent.ts\`)

Every tool the playground exposes via \`@inbrowser/agent\`'s
\`buildTools\` shape. Each is a candidate for re-implementation
against a piebox-native tool descriptor.

EOF
  grep -nE "const [a-zA-Z]+: ToolHandler = \{" examples/browser/src/agent.ts \
    | sed -E 's/^([0-9]+):.*const ([a-zA-Z]+): ToolHandler.*$/- L\1: `\2`/'
  echo
  cat <<EOF

Total: $(grep -cE "const [a-zA-Z]+: ToolHandler = \{" examples/browser/src/agent.ts) tool definitions.

Each tool's \`execute\` takes \`(args, ctx: ToolContext)\` where
\`ctx\` is supplied by \`@inbrowser/agent\`. The tools currently use
only \`ctx.signal\`; \`ctx.workspace\` and \`ctx.runtime\` are
present in the type but never read.

EOF
}

emit_session_event_consumers() {
  cat <<EOF
## SessionEvent kinds consumed by the playground

In \`examples/browser/src/agent/useAgentLoop.ts\` the \`handleEvent\`
switch branches on these \`SessionEvent.kind\` values:

EOF
  grep -E "case '(turn_started|text|thinking|tool_started|tool_finished|turn_completed|error|completed)'" examples/browser/src/agent/useAgentLoop.ts \
    | sed -E "s/^[[:space:]]*case '([^']+)':?.*$/- \\1/" \
    | sort -u
  echo
  cat <<EOF

Notable: \`strategy_event\`, \`workspace_changed\`, and
\`runtime_changed\` are defined in the union but **never** consumed by
the playground. If they aren't consumed by any other driver either
(to be checked in investigation C), they may not need to be part of a
piebox-native streaming contract at all.

EOF
}

emit_summary_counts() {
  cat <<EOF
## Headline counts

| Metric                                                       | Value |
| ------------------------------------------------------------ | ----- |
| Total \`.ts\` files in \`src/\`                              | $(find src -type f -name "*.ts" -not -path "*/node_modules/*" | wc -l | tr -d ' ') |
| \`src/\` files importing \`@earendil-works/*\`               | $(grep -rl "@earendil-works" src/ 2>/dev/null | wc -l | tr -d ' ') |
| Import statements of \`@earendil-works/*\` across \`src/\`   | $(grep -r "@earendil-works" src/ 2>/dev/null | wc -l | tr -d ' ') |
| \`examples/browser/src/\` files importing \`@inbrowser/agent\` | $(grep -rl "@inbrowser/agent" examples/browser/src/ 2>/dev/null | wc -l | tr -d ' ') |
| \`ToolHandler\` definitions in playground                    | $(grep -cE "const [a-zA-Z]+: ToolHandler = \{" examples/browser/src/agent.ts) |
| \`SessionEvent\` kinds the playground handles                | $(grep -cE "case '(turn_started|text|thinking|tool_started|tool_finished|turn_completed|error|completed)'" examples/browser/src/agent/useAgentLoop.ts) |

EOF
}

emit_implications() {
  cat <<EOF
## Implications for the refactor (rough — to be revised against C/G)

1. **Layer 2 must define its own operation types.** \`src/operations/\`
   currently can't be lifted into a protocol-neutral surface because
   its types come from \`@earendil-works/pi-coding-agent\`. The refactor
   has to introduce piebox-native \`ReadOperations\` /
   \`WriteOperations\` / etc. type aliases — then both SDKs adapt.

2. **The agent driver wraps two SDKs, not one.** A \`@piebox/driver-agent\`
   package would have to either (a) pick one SDK and have the other
   adapt to it, (b) ship sub-drivers for both, or (c) define its own
   agent-driver-internal types and have both SDKs adapt. Option (c)
   is consistent with the Layer 2 principle.

3. **\`ToolContext\` carries fields the tools don't use.** The
   browser playground's tools never read \`ctx.workspace\` or
   \`ctx.runtime\` — only \`ctx.signal\`. The piebox-native tool
   descriptor can be much leaner: \`(args, sandbox, signal) =>
   PieboxResult<T>\`.

4. **\`SessionEvent\` has dead branches in the playground.** The
   playground does not consume \`strategy_event\`, \`workspace_changed\`,
   or \`runtime_changed\`. If MCP and CLI drivers also don't, those
   shapes are pure agent-driver concern and never need to exist in
   Layer 2.

5. **Scope of the refactor (rough):** 16 \`src/\` files touch the
   server-side SDK; 2 \`examples/browser/src/\` files touch the
   browser-side SDK. The browser surface is smaller and likely
   cheaper to refactor first.

EOF
}

emit_header
emit_finding_two_sdks
emit_sdk_inventory "@earendil-works/pi-coding-agent" "@earendil-works/pi-coding-agent"
emit_sdk_inventory "@inbrowser/agent" "@inbrowser/agent"
emit_type_leaks_pi_coding_agent
emit_browser_surface
emit_tool_inventory
emit_session_event_consumers
emit_summary_counts
emit_implications
